Components/TourDaHuyMienBacViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using YourTour.Service;

namespace YourTour.Components
{
    public class TourDaHuyMienBacViewComponent : ViewComponent
    {
        private readonly AdminService _adminService;
        public TourDaHuyMienBacViewComponent(AdminService adminService)
        {
            this._adminService = adminService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = this._adminService.GetAllTourDaHuyMienBac();
            return View(model);
        }
    }
}

Components/TourDaHuyMienNamViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using YourTour.Service;

namespace YourTour.Components
{
    public class TourDaHuyMienNamViewComponent : ViewComponent
    {
        private readonly AdminService _adminService;
        public TourDaHuyMienNamViewComponent(AdminService adminService)
        {
            this._adminService = adminService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = this._adminService.GetAllTourDaHuyMienNam();
            return View(model);
        }
    }
}

Controllers/DiaDiemController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YourTour.Models.db;
using YourTour.Service;

namespace YourTour.Controllers
{
    public class DiaDiemController : Controller
    {
        private readonly LocationService _locationService;
        private readonly YourTourContext _db;

        public DiaDiemController(LocationService locationService, YourTourContext db)
        {
            this._locationService = locationService;
            this._db = db;
        }
    }
}

Controllers/TourController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YourTour.Models.Commands;
using YourTour.Models.db;
using YourTour.Models.ViewModels;
using YourTour.Service;

namespace YourTour.Controllers
{
    public class TourController : Controller
    {
        private readonly TourService _tourService;
        private readonly TravelService _travelService;
        private readonly YourTourContext _db;

        public TourController(TourService tourService, YourTourContext db, TravelService travelService)
        {
            this._tourService = tourService;
            this._travelService = travelService;
            this._db = db;
        }
        public IActionResult TourTrongNuoc()
        {
            var model = this._tourService.TourTrongNuoc();
            return View(model);
        }
        public IActionResult TourMienNam(int? id)
        {
            if (id == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            var model = this._tourService.ChiTietTourMienNam(id);
            if (model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult TourMienBac(int? id)
        {
            if (id == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            var model = this._tourService.ChiTietTourMienBac(id);
            if (model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult TourMienTrung(int? id)
        {
            if (id == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            var model = this._tourService.ChiTietTourMienTrung(id);
            if (model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult ShowAllTourMienBac()
        {
            var model = this._tourService.ShowAllTourMienBac();
            if(model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult ShowAllTourMienTrung()
        {
            var model = this._tourService.ShowAllTourMienTrung();
            if (model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult ShowAllTourMienNam()
        {
            var model = this._tourService.ShowAllTourMienNam();
            if (model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult TourNgoaiNuoc()
        {
            return View();
        }
        public IActionResult ChiTietTour(int? id)
        {
            if (id == null)
            {
                return View("/Views/Shared/Error.cshtml");
            }
            var model = this._tourService.ChiTietTour(id);
            if (model == null)
            {
                return null;
            }

            return View(model);
        }
        [HttpGet]
        public IActionResult XoaTour(int id)
        {
            var model = this._travelService.SeeTour(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult TimTour(string diemDen, DateTime ngayDi)
        {
            var model = this._tourService.TimTour(diemDen, ngayDi);
            if (model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult XoaTour(InsertTourCommand viewModel)
        {
            if (viewModel.ID == null)
            {
                return View("/Views/Shared/Error.cshtml");
            }
            this._tourService.XoaTour(viewModel);
            return RedirectToAction("ShowAllTour", "Admin");
        }
    }
}

Views/Admin/AddLocation.cshtml
@model YourTour.Models.Commands.LocationCommand
@{
    ViewData["Title"] = "AddLocation";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@{<h1 style = "text-align:center;color:brown;text-transform:uppercase" > Thêm địa điểm du lịch mới</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("AddLocation", "Admin", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Tendiadiem" class="control-label">Tên địa điểm</label>
                <input name="Tendiadiem" class="form-control" />
                <span asp-validation-for="Tendiadiem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mota" class="control-label">Mô tả</label>
                <input name="Mota" class="form-control" />
                <span asp-validation-for="Mota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MienID" class="control-label">Tên miền</label>
                <select asp-for="MienID" class="form-control" name="MienID" asp-items="@(new SelectList(@ViewBag.ListMien, "ID", "Tenmien"))">
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Thêm địa điểm du lịch mới" class="btn btn-primary" />
            </div>
        }
    </div>
</div> 
}

Views/Admin/AddStaff.cshtml
@model YourTour.Models.ViewModels.NhanvienViewModel
@{
    ViewData["Title"] = "AddStaff";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1 style="text-align:center;color:brown;text-transform:uppercase">Thêm nhân viên mới</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("AddStaff", "Admin", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Hoten" class="control-label">Tên nhân viên</label>
                <input name="Hoten" class="form-control" />
                <span asp-validation-for="Hoten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sdt" class="control-label">Số điện thoại</label>
                <input name="Sdt" class="form-control" />
                <span asp-validation-for="Sdt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gioitinh" class="control-label">Giới tính</label>
                <select class="form-control" name="Gioitinh">
                    <option value="Nam">Nam</option>
                    <option value="Nữ">Nữ</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email</label>
                <input name="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matkhau" class="control-label">Mật khẩu</label>
                <input type="password" name="Matkhau" class="form-control" />
                <span asp-validation-for="Matkhau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vaitro" class="control-label">Vai trò</label>
                <input name="Vaitro" class="form-control" />
                <span asp-validation-for="Vaitro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Thêm nhân viên mới" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

Views/Admin/AllLocation.cshtml
@model IEnumerable<YourTour.Models.Commands.LocationCommand>

@{
    ViewData["Title"] = "AllLocation";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1 style="text-align:center;color:brown">Danh sách địa điểm </h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Tendiadiem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MienID)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Email)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Tendiadiem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mota)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MienID)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>*@
                <td>
                    @Html.ActionLink("Sửa", "EditLocation", "Admin", new { id = item.ID }) |
                    @*@Html.ActionLink("Chi tiết", "DetailLocation", "DiaDiem", new { id = item.ID }) |*@
                    @Html.ActionLink("Xóa", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Admin/DanhSachYeuCauTuVanDaXacNhan.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<YourTour.Models.ViewModels.TourTuyChonViewModel>
@{
    ViewData["Title"] = "DanhSachTourTuyChon";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h2>Danh sách khách đặt tour tùy chọn</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().TenKH)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Sdt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Mien)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Songuoidi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Ngaykhoihanh)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenKH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sdt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mien)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Songuoidi)
                </td>
                <td>
                    @item.Ngaykhoihanh.ToShortDateString()
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Admin/EditLocation.cshtml
@model YourTour.Models.ViewModels.DiadiemViewModel

@{
    ViewData["Title"] = "EditLocation";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1 style="text-align:center;color:brown">Chỉnh sửa thông tin @Model.Tendiadiem</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("EditLocation", "Admin", FormMethod.Post))
        {
            <input type="hidden" name="@Model.ID" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label name="Tendiadiem" class="control-label">Tên địa điểm</label>
                <input name="Tendiadiem" class="form-control" value="@Model.Tendiadiem" />
                <span asp-validation-for="Tendiadiem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label name="Mota" class="control-label">Mô tả</label>
                <input name="Mota" class="form-control" value="@Model.Mota" />
                <span asp-validation-for="Mota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label name="MienID" class="control-label">Tên miền</label>
                <select class="form-control" name="MienID" asp-items="@(new SelectList(@ViewBag.ListMien, "ID", "Tenmien"))" value="@Model.MienID">
                </select>
            </div>
            @*<div class="form-group">
                <label name="Gioitinh" class="control-label">Giới tính</label>
                <select class="form-control" name="Gioitinh">
                    <option value="Nam">Nam</option>
                    <option value="Nữ">Nữ</option>
                </select>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        }
    </div>
</div>

Views/Admin/EditStaff.cshtml
@model YourTour.Models.ViewModels.NhanvienViewModel

@{
    ViewData["Title"] = "EditStaff";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1 style="text-align:center;color:brown">Chỉnh sửa thông tin nhân viên</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("EditStaff", "Admin", FormMethod.Post))
        {
            <input type="hidden" name="@Model.ID" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label name="Hoten" class="control-label">Tên nhân viên</label>
                <input name="Hoten" class="form-control" value="@Model.Hoten" id="Hoten" @*onchange="return KiemTra()"*@/>
                <span asp-validation-for="Hoten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label name="Sdt" class="control-label">Số điện thoại</label>
                <input name="Sdt" class="form-control" value="@Model.Sdt" id="Sdt" @*onchange="return KiemTra()"*@/>
                <span asp-validation-for="Sdt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label name="Gioitinh" class="control-label">Giới tính</label>
                <select class="form-control" name="Gioitinh">
                    <option value="Nam">Nam</option>
                    <option value="Nữ">Nữ</option>
                </select>
            </div>
            <div class="form-group">
                <label name="Email" class="control-label">Email</label>
                <input name="Email" class="form-control" value="@Model.Email" id="Email" @*onchange="return KiemTra()"*@/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label name="Matkhau" class="control-label">Mật khẩu</label>
                <input name="Matkhau" class="form-control" value="@Model.Matkhau" id="Matkhau" @*onchange="return KiemTra()"*@/>
                <span asp-validation-for="Matkhau" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label name="Vaitro" class="control-label">Vai trò</label>
                <input name="Vaitro" class="form-control" value="@Model.Vaitro" id="Vaitro" @*onchange="return KiemTra()"*@/>
                <span asp-validation-for="Vaitro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-success" @*onclick="KiemTra()"*@/>
            </div>
        }
    </div>
</div>
@*<script>
    function Rong() {
        if (document.getElementById("Vaitro").value == "") {
            return console.alert("ssssssssssss");
        }
    }
    function KiemTra() {
        var Name, Phone, Email, Pass, Role, emailexp, phoneexp;
        Name = document.getElementById("Hoten").value;
        Phone = document.getElementById("Sdt").value;
        Email = document.getElementById("Email").value;
        Pass = document.getElementById("Matkhau").value;
        Role = document.getElementById("Vaitro").value;
        emailexp = /^([\w\.\-]+)@@([\w\-]+)((\.(\w){2,3})+)$/;
        phoneexp = /^(09|01[2|6|8|9])+([0-9]{8})$/;
        if (Name == "" && Phone == 0 && Email == "" && Pass == "" && Role == "")
        {
            alert("Không được để trống !!!");
            return false;
        }
        if (Name == "") {
            alert("Vui lòng nhập tên");
            return false;
        }
        if (Phone == "")
        {
           alert("Vui lòng nhập số điện thoại");
           return false;
        }
        if (Email == "")
        {
             alert("Vui lòng nhập email");
             return false;
        }
        if (Pass == "")
        {
            alert("Vui lòng nhập mật khẩu");
            return false;
        }
        if (Role == "")
        {
            alert("Vui lòng nhập vai trò");
            return false;
        }
        if (Email != "")
        {
            if (!Email.match(emailexp))
            {
                alert("Email không hợp lệ");
                return false;
             }
        }
        if (Phone != "")
        {
            if (!Phone.match(phoneexp))
            {
                alert("Số điện thoại không hợp lệ");
                return false;
            }
        }
        return true;
    }
</script>*@

Views/Admin/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "Admin Page";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Admin</title>
</head>
<body>
    <h1>Hello Admin</h1>
</body>
</html>

Views/Admin/ShowAllBookingTour.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<YourTour.Models.ViewModels.CommonViewModel>;
@{
    ViewData["Title"] = "ShowAllBookingTour";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h1 style="color:brown;text-align:center">Danh sách tour đã đặt</h1>

<input id="myInput" type="text" placeholder="Search..">
<table class="table" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hoadoncode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ngaylaphd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Thuocmien)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tongtien)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ptthanhtoan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tinhtrang)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hoten)
            </th>
        </tr>
    </thead>
    <tbody id="myTable">
        @await Component.InvokeAsync("BookingTourMienNam")
        @await Component.InvokeAsync("BookingTourMienBac")
        @await Component.InvokeAsync("BookingTourMienTrung")
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
    setTimeout(function () {
        location.reload();
    }, 5000);
</script>

Views/Admin/ShowAllTour.cshtml
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@*@using X.PagedList.Web.Common;*@
@model IPagedList<YourTour.Models.ViewModels.TourViewModel>

@{
    ViewData["Title"] = "ShowAllTour";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1 style="color:brown;text-align:center">Danh sách tour du lịch</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Tentour)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Diemden)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.First().Diadiemkhoihanh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Ngaydi)
            </th>*@
            @*<th>
                @Html.DisplayNameFor(model => model.First().Ngayve)
            </th>*@
            @*<th>
                @Html.DisplayNameFor(model => model.First().Lichtrinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Hinhanh)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.First().Gianguoilon)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.First().Giatreem)
            </th>*@
            @*<th>
                @Html.DisplayNameFor(model => model.First().TenHDV)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.First().Trangthai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Songuoi)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <input type="hidden" name="@item.ID" />
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tentour)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diemden)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Diadiemkhoihanh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ngaydi)
            </td>*@
            @*<td>
                @Html.DisplayFor(modelItem => item.Ngayve)
            </td>*@
            @*<td>
                @Html.DisplayFor(modelItem => item.Lichtrinh)
            </td>
            <td>
                <img src="@Url.Content("/images/tour_images/" + item.Hinhanh)" style="width:150px;height:200px;" />
            </td>*@
            <td>
                @item.Gianguoilon.ToString("#,##") VNĐ
            </td>
            @*<td>
                @item.Giatreem.ToString("#,##") VNĐ
            </td>*@
            @*<td>
                @Html.DisplayFor(modelItem => item.TenHDV)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Trangthai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Songuoi)
            </td>

            <td>
                @Html.ActionLink("Sửa", "EditTour", "Admin", new { id = item.ID }) |
                @Html.ActionLink("Chi tiết", "ChiTietTour", "Tour", new { id = item.ID }) |
                @Html.ActionLink("Xóa", "XoaTour", "Tour", new { id = item.ID })
            </td>
        </tr>
        }
    </tbody>
</table>
<br />
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("ShowAllTour", new { page }))

Views/Admin/ShowChiTietThongTinBooking.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model YourTour.Models.ViewModels.CommonViewModel
@{ 
    ViewData["Title"] = "ThongTinChiTietBooking";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@Model.Hoadoncode
@Model.Hoten

Views/Admin/ShowChiTietThongTinBookingTourMienBac.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model YourTour.Models.ViewModels.CommonViewModel
@{ 
    ViewData["Title"] = "ThongTinChiTietBooking";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h1 style="text-align:center">Thông tin chi tiết tour đã đặt</h1>

Views/Admin/ShowTourDaHuy.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<YourTour.Models.ViewModels.CommonViewModel>;
@{
    ViewData["Title"] = "ShowAllBookingTour";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h1 style="color:brown;text-align:center">Danh sách tour đã hủy</h1>

<input id="myInput" type="text" placeholder="Search..">
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hoadoncode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ngaylaphd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Thuocmien)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tongtien)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hoten)
            </th>
        </tr>
    </thead>
    <tbody>
        @await Component.InvokeAsync("TourDaHuyMienNam")
        @await Component.InvokeAsync("TourDaHuyMienBac")
        @await Component.InvokeAsync("TourDaHuyMienTrung")
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>