Controllers/KhachSanController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YourTour.Service;

namespace YourTour.Controllers
{
    public class KhachSanController : Controller
    {
        private readonly KhachSanService _khachSanService;
        public KhachSanController(KhachSanService khachSanService)
        {
            this._khachSanService = khachSanService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult DiemDen()
        {
            return View();
        }
        public IActionResult KhachSanThuocDiaDiem(int id)
        {
            var model = this._khachSanService.KsMienTrung(id);
            if(model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
    }
}

Controllers/TourController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YourTour.Models.Commands;
using YourTour.Models.db;
using YourTour.Models.ViewModels;
using YourTour.Service;

namespace YourTour.Controllers
{
    public class TourController : Controller
    {
        private readonly TourService _tourService;
        private readonly TravelService _travelService;
        private readonly YourTourContext _db;

        public TourController(TourService tourService, YourTourContext db, TravelService travelService)
        {
            this._tourService = tourService;
            this._travelService = travelService;
            this._db = db;
        }
        public IActionResult TourTrongNuoc()
        {
            var model = this._tourService.TourTrongNuoc();
            return View(model);
        }
        public IActionResult TourMienNam(int? id)
        {
            if (id == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            var model = this._tourService.ChiTietTourMienNam(id);
            if (model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult TourMienBac(int? id)
        {
            if (id == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            var model = this._tourService.ChiTietTourMienBac(id);
            if (model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult TourMienTrung(int? id)
        {
            if (id == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            var model = this._tourService.ChiTietTourMienTrung(id);
            if (model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult ShowAllTourMienBac()
        {
            var model = this._tourService.ShowAllTourMienBac();
            if(model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult ShowAllTourMienTrung()
        {
            var model = this._tourService.ShowAllTourMienTrung();
            if (model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult ShowAllTourMienNam()
        {
            var model = this._tourService.ShowAllTourMienNam();
            if (model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult TourNgoaiNuoc()
        {
            return View();
        }
        public IActionResult ChiTietTour(int? id)
        {
            if (id == null)
            {
                return View("/Views/Shared/Error.cshtml");
            }
            var model = this._tourService.ChiTietTour(id);
            if (model == null)
            {
                return null;
            }

            return View(model);
        }
        [HttpGet]
        public IActionResult XoaTour(int id)
        {
            var model = this._travelService.SeeTour(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult TimTour(string diemDen, DateTime ngayDi)
        {
            var model = this._tourService.TimTour(diemDen, ngayDi);
            if (model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
        public IActionResult XoaTour(InsertTourCommand viewModel)
        {
            if (viewModel.ID == null)
            {
                return View("/Views/Shared/Error.cshtml");
            }
            this._tourService.XoaTour(viewModel);
            return RedirectToAction("ShowAllTour", "Admin");
        }
    }
}

Views/Shared/PageNotFound.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "PageNotFound";
    Layout = "~/Views/Shared/_LayoutTour.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <link href="/css/error.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <div class="face">
        <div class="band">
            <div class="red"></div>
            <div class="white"></div>
            <div class="blue"></div>
        </div>
        <div class="eyes"></div>
        <div class="dimples"></div>
        <div class="mouth"></div>
    </div>

    <h1>Oops! Something went wrong!</h1>
    <div class="btn"><a href="@Url.Action("Index","Home")">Back to home</a></div>
</body>
</html>

Views/Shared/_LayoutLogin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">

    <!--css-->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <!--js-->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!--style-->
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #17a2b8;
            height: 100vh;
        }

        #login .container #login-row #login-column #login-box {
            margin-top: 120px;
            max-width: 600px;
            height: 320px;
            border: 1px solid #9C9C9C;
            background-color: #EAEAEA;
        }

            #login .container #login-row #login-column #login-box #login-form {
                padding: 20px;
            }

                #login .container #login-row #login-column #login-box #login-form #register-link {
                    margin-top: -85px;
                }
    </style>
</head>
<body>
    @RenderBody()
</body>
</html>

Views/Shared/_LayoutTour.cshtml
<!--
author: W3layouts
author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Tenlua Travel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">

    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>

    <!-- css files -->
    <link href="/css/bootstrap.css" rel='stylesheet' type='text/css' /><!-- bootstrap css -->
    <link href="/css/style.css" rel='stylesheet' type='text/css' /><!-- custom css -->
    <link href="/css/font-awesome.min.css" rel="stylesheet"><!-- fontawesome css -->
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/css/social_icon.css" rel="stylesheet" type="text/css" /><!--custom social icon-->
    <link href="/css/main-menu.css" rel="stylesheet" type="text/css" /><!--custom menu-->
    <!-- //css files -->
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300&display=swap" rel="stylesheet">
    @*<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
        <link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">*@
    <!-- //google fonts -->

</head>
<body>
    <div class="pagination justify-content-end" id="search">
        <form method="post" action="@Url.Action("TimTour","Home")" style="margin:0 30px 0 0">
            <input type="text" name="diemDen" placeholder="Điểm đến ..." style="border:none" />
            <button type="submit" style="border:none;background-color:transparent " class="btn btn-light fa fa-search"></button>
        </form>
    </div>
    <!-- header -->
    <header>
        <div class="container">
            <!-- nav -->
            <nav class="py-md-4 py-3 d-lg-flex">
                <div id="logo">
                    <h1 class="mt-md-0 mt-2"> <a href="@Url.Action("Index","Home")"><span class="fas fa-rocket"></span> Tenlua Travel </a></h1>
                    <h6 class="mt-md-0 mt-2"><a href="#"><span>Be An Adventurer</span></a></h6>
                </div>
                <label for="drop" class="toggle"><span class="fa fa-bars"></span></label>
                <input type="checkbox" id="drop" />
                <ul class="menu ml-auto mt-1" id="main-menu">
                    <li class="active"><a href="@Url.Action("Index","Home")">Trang chủ</a></li>
                    <li class="active">
                        <a href="@Url.Action("TourTrongNuoc","Tour")">Du lịch</a>
                        <ul class="menu ml-auto mt-0 overlay-inner">
                            <li class="active"><a href="@Url.Action("ShowAllTourMienBac","Tour")">Du lịch miền Bắc</a></li>
                            <li class="active"><a href="@Url.Action("ShowAllTourMienTrung","Tour")">Du lịch miền Trung</a></li>
                            <li class="active"><a href="@Url.Action("ShowAllTourMienNam","Tour")">Du lịch miền Nam</a></li>
                            <li class="active"><a href="@Url.Action("DiemDen","KhachSan")">Du lịch tự chọn</a></li>
                        </ul>
                    </li>
                    <li class="active"><a href="https://tripu.vn/vi/hotels">Khách sạn</a></li>
                    <li class="active">
                        <a href="https://www.worldtrans.vn/">Vận chuyển</a>
                        <ul class="menu ml-auto mt-0 overlay-inner">
                            <li class="active"><a href="http://car4rent.com/">Thuê xe</a></li>
                            <li class="active"><a href="https://www.worldtrans.vn/">Vé máy bay</a></li>
                        </ul>
                    </li>
                    <li class="active">
                        <a href="@Url.Action("TinTuc","Home")">Tin tức</a>
                        <ul class="menu ml-auto mt-0 overlay-inner">
                            <li class="active"><a href="@Url.Action("TinTuc","Home")">Tin tức</a></li>
                            <li class="active" style="width:auto"><a href="@Url.Action("KinhNghiemDuLich","Home")">Kinh nghiệm du lịch</a></li>
                        </ul>
                    </li>
                    <li class="active">
                        <a href="#">Khuyến mãi</a>
                        <ul class="menu ml-auto mt-0 overlay-inner">
                            <li class="active"><a href="#">Ưu đãi One Pay</a></li>
                            <li class="active"><a href="#">Ưu đãi Viettin Bank</a></li>
                        </ul>
                    </li>
                    <li class="active"><a href="@Url.Action("LienHe","Home")">Liên hệ</a></li>
                </ul>
            </nav>
            <!-- //nav -->
        </div>
    </header>
    <div style="height:28px; background-color:lightgray"></div>
    <!-- //header -->
    <!-- banner -->
    @*<section class="banner_inner" id="home">
            <div class="banner_inner_overlay">
            </div>
        </section>*@
    <!-- //banner -->
    <!-- tour packages -->
    <section class="packages pt-5">
        @RenderBody()
        <!--social-->
        <div class="overlay-1">
            <div class="icon-bar">
                <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                <a href="#" class="messenger"><i class="fab fa-facebook-messenger"></i></a>
            </div>
        </div>
    </section>
    <!-- tour packages -->
    <!--footer -->
    <footer>
        <section class="footer footer_w3layouts_section_1its py-5">
            <div class="container py-lg-4 py-3">
                <div class="row footer-top">
                    <div class="col-lg-4 col-sm-6 footer-grid_section_1its_w3">
                        <div class="footer-title">
                            <h3>Địa chỉ</h3>
                        </div>
                        <div class="footer-text">
                            <p>Công ty CP Du lịch và Tiếp thị GTVT Tên Lửa Travel</p>
                            <p>Location : 12 Nguyễn Văn Bảo, phường 4, quận Gò Vấp</p>
                            <p>Phone : +84 369052254</p>
                            <p>Email : <a href="mailto:tenluatravel.services@gmail.com">tenluatravel.services@gmail.com</a></p>
                        </div>
                    </div>
                    <div class="col-lg-5 col-sm-6 mt-lg-0 mt-4 footer-grid_section_1its_w3">
                        <div class="footer-title">
                            <h3>Thông Tin</h3>
                        </div>
                        <div class="row">
                            <ul class="col-6 links">
                                <li><a href="#choose" class="scroll">Tạp chí du lịch </a></li>
                                <li><a href="#overview" class="scroll">Cẩm nang du lịch </a></li>
                                <li><a href="#pricing" class="scroll">Kinh nghiệm du lịch</a></li>
                                <li><hr style="color:#fff" /></li>
                                <li><a href="#faq" class="scroll"> Chính sách riêng tư</a></li>
                                <li><a href="#testimonials" class="scroll">Thỏa thuận sử dụng</a></li>
                            </ul>
                            <ul class="col-6 links">
                                <li><a href="#">Tin tức</a></li>
                                <li><a href="#">Sitemap</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 mt-lg-0 mt-4 footer-grid_section_1its_w3">
                        <div class="footer-title">
                            <h3>Newsletter</h3>
                        </div>
                        <div class="footer-text">
                            <p>
                                Bằng cách đăng ký vào danh sách gửi thư của chúng tôi, bạn sẽ luôn nhận được tin tức và cập nhật mới nhất từ ​​chúng tôi.
                            </p>
                            <form action="#" method="post">
                                <input type="email" name="Email" placeholder="Enter your email..." required="">
                                <button class="btn1"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                                <div class="clearfix"> </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </footer>
    <!-- //footer -->
    <!-- move top -->
    <div class="move-top text-right">
        <a href="#home" class="move-top">
            <span class="fa fa-angle-up  mb-3" aria-hidden="true"></span>
        </a>
    </div>
    <!-- move top -->


</body>
</html>

Views/Shared/_LayoutTourDetail.cshtml
<html lang="en">
<head>
    <title>Tenlua Travel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">

    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>

    <!-- css files -->
    <link href="/css/bootstrap.css" rel="stylesheet" type="text/css"><!-- bootstrap css -->
    <link href="/css/style.css" rel="stylesheet" type="text/css"><!-- custom css -->
    <link href="/css/font-awesome.min.css" rel="stylesheet"><!-- fontawesome css -->
    <link href="/css/main-menu.css" rel="stylesheet" type="text/css" /><!--custom menu-->
    <!-- //css files -->
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300&display=swap" rel="stylesheet">
    @*<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
        <link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">*@
    <!-- //google fonts -->

</head>
<body>
    <div class="pagination justify-content-end" id="search">
        <form method="post" action="@Url.Action("TimTour","Home")" style="margin:0 30px 0 0">
            <input type="text" name="diemDen" placeholder="Điểm đến ..." style="border:none" />
            <button type="submit" style="border:none;background-color:transparent " class="btn btn-light fa fa-search"></button>
        </form>
    </div>
    <!-- header -->
    <header>
        <div class="container">
            <!-- nav -->
            <nav class="py-md-4 py-3 d-lg-flex">
                <div id="logo">
                    <h1 class="mt-md-0 mt-2"> <a href="@Url.Action("Index","Home")"><span class="fas fa-rocket"></span> Tenlua Travel </a></h1>
                    <h6 class="mt-md-0 mt-2"><a href="#"><span>Be An Adventurer</span></a></h6>
                </div>
                <label for="drop" class="toggle"><span class="fa fa-bars"></span></label>
                <input type="checkbox" id="drop" />
                <ul class="menu ml-auto mt-1" id="main-menu">
                    <li class="active"><a href="@Url.Action("Index","Home")">Trang chủ</a></li>
                    <li class="active">
                        <a href="@Url.Action("TourTrongNuoc","Tour")">Du lịch</a>
                        <ul class="menu ml-auto mt-0 overlay-inner">
                            <li class="active"><a href="@Url.Action("ShowAllTourMienBac","Tour")">Du lịch miền Bắc</a></li>
                            <li class="active"><a href="@Url.Action("ShowAllTourMienTrung","Tour")">Du lịch miền Trung</a></li>
                            <li class="active"><a href="@Url.Action("ShowAllTourMienNam","Tour")">Du lịch miền Nam</a></li>
                            <li class="active"><a href="@Url.Action("DiemDen","KhachSan")">Du lịch tự chọn</a></li>
                        </ul>
                    </li>
                    <li class="active"><a href="https://tripu.vn/vi/hotels">Khách sạn</a></li>
                    <li class="active">
                        <a href="https://www.worldtrans.vn/">Vận chuyển</a>
                        <ul class="menu ml-auto mt-0 overlay-inner">
                            <li class="active"><a href="http://car4rent.com/">Thuê xe</a></li>
                            <li class="active"><a href="https://www.worldtrans.vn/">Vé máy bay</a></li>
                        </ul>
                    </li>
                    <li class="active">
                        <a href="@Url.Action("TinTuc","Home")">Tin tức</a>
                        <ul class="menu ml-auto mt-0 overlay-inner">
                            <li class="active"><a href="@Url.Action("TinTuc","Home")">Tin tức</a></li>
                            <li class="active" style="width:auto"><a href="@Url.Action("KinhNghiemDuLich","Home")">Kinh nghiệm du lịch</a></li>
                        </ul>
                    </li>
                    <li class="active">
                        <a href="#">Khuyến mãi</a>
                        <ul class="menu ml-auto mt-0 overlay-inner">
                            <li class="active"><a href="#">Ưu đãi One Pay</a></li>
                            <li class="active"><a href="#">Ưu đãi Viettin Bank</a></li>
                        </ul>
                    </li>
                    <li class="active"><a href="@Url.Action("LienHe","Home")">Liên hệ</a></li>
                </ul>
            </nav>
            <!-- //nav -->
        </div>
    </header>
    <div style="height:28px; background-color:lightgray"></div>
    <!-- //header -->
    <!-- banner -->
    @*<section class="banner_inner" id="home">
            <div class="banner_inner_overlay">
            </div>
        </section>*@
    <!-- //banner -->
    <!-- Booking -->
    <section class="contact py-5">
        @RenderBody()
    </section>
    <!-- //Booking -->
    <!--footer -->
    <footer>
        <section class="footer footer_w3layouts_section_1its py-5">
            <div class="container py-lg-4 py-3">
                <div class="row footer-top">
                    <div class="col-lg-4 col-sm-6 footer-grid_section_1its_w3">
                        <div class="footer-title">
                            <h3>Địa chỉ</h3>
                        </div>
                        <div class="footer-text">
                            <p>Công ty CP Du lịch và Tiếp thị GTVT Tên Lửa Travel</p>
                            <p>Location : 12 Nguyễn Văn Bảo, phường 4, quận Gò Vấp</p>
                            <p>Phone : +84 369052254</p>
                            <p>Email : <a href="mailto:tenluatravel.services@gmail.com">tenluatravel.services@gmail.com</a></p>
                        </div>
                    </div>
                    <div class="col-lg-5 col-sm-6 mt-lg-0 mt-4 footer-grid_section_1its_w3">
                        <div class="footer-title">
                            <h3>Thông Tin</h3>
                        </div>
                        <div class="row">
                            <ul class="col-6 links">
                                <li><a href="#choose" class="scroll">Tạp chí du lịch </a></li>
                                <li><a href="#overview" class="scroll">Cẩm nang du lịch </a></li>
                                <li><a href="#pricing" class="scroll">Kinh nghiệm du lịch</a></li>
                                <li><hr style="color:#fff" /></li>
                                <li><a href="#faq" class="scroll"> Chính sách riêng tư</a></li>
                                <li><a href="#testimonials" class="scroll">Thỏa thuận sử dụng</a></li>
                            </ul>
                            <ul class="col-6 links">
                                <li><a href="#">Tin tức</a></li>
                                <li><a href="#">Sitemap</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 mt-lg-0 mt-4 footer-grid_section_1its_w3">
                        <div class="footer-title">
                            <h3>Newsletter</h3>
                        </div>
                        <div class="footer-text">
                            <p>
                                Bằng cách đăng ký vào danh sách gửi thư của chúng tôi, bạn sẽ luôn nhận được tin tức và cập nhật mới nhất từ ​​chúng tôi.
                            </p>
                            <form action="#" method="post">
                                <input type="email" name="Email" placeholder="Enter your email..." required="">
                                <button class="btn1"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                                <div class="clearfix"> </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </footer>
    <!-- //footer -->
    <!-- move top -->
    <div class="move-top text-right">
        <a href="#home" class="move-top">
            <span class="fa fa-angle-up  mb-3" aria-hidden="true"></span>
        </a>
    </div>
    <!-- move top -->
</body>
</html>