Models/ViewModels/KhachSanViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel;

namespace YourTour.Models.ViewModels
{
    public class KhachSanViewModel
    {
        public int ID { get; set; }
        [DisplayName("Tên khách sạn")]
        public string Tenks { get; set; }
        [DisplayName("Hình ảnh")]
        public string Hinhanh { get; set; }
        [DisplayName("Mô tả")]
        public string Mota { get; set; }
        [DisplayName("Địa chỉ")]
        public string Diachi { get; set; }
        [DisplayName("Giá")]
        public int Gia { get; set; }
        [DisplayName("Số điện thoại")]
        public string Sdt { get; set; }
        [DisplayName("Tiện nghi phòng")]
        public string Thongtinphong { get; set; }
        public string Loaiphong { get; set; }
        public int Giaphuthu { get; set; }
        public int Giatreem { get; set; }
        public int DiadiemID { get; set; }
    }
}

Models/db/KhachSan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;
using YourTour.Models.ViewModels;

namespace YourTour.Models.db
{
    public class KhachSan
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public string Tenks { get; set; }
        public string Hinhanh { get; set; }
        public string Mota { get; set; }
        public string Diachi { get; set; }
        public string Sdt { get; set; }
        public string Loaiphong { get; set; }
        public string Thongtinphong { get; set; }
        public int Gia { get; set; }
        public int Giaphuthu { get; set; }
        public int Giatreem { get; set; }
        public int DiaDiemID { get; set; }
        public Diadiemdulich Diadiemdulich { get; set; }

        public KhachSan() { }
        public KhachSan(KhachSanViewModel ks)
        {
            this.ID = ks.ID;
            this.Tenks = ks.Tenks;
            this.Hinhanh = ks.Hinhanh;
            this.Mota = ks.Mota;
            this.Diachi = ks.Diachi;
            this.Gia = ks.Gia;
            this.Giaphuthu = ks.Giaphuthu;
            this.Giatreem = ks.Giatreem;
            this.Sdt = ks.Sdt;
            this.DiaDiemID = ks.DiadiemID;
            this.Thongtinphong = ks.Thongtinphong;
            this.Loaiphong = ks.Loaiphong;
        }
    }
}

Components/DiaDiemMienTrungViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YourTour.Service;

namespace YourTour.Components
{
    public class DiaDiemMienTrungViewComponent : ViewComponent
    {
        private readonly DiaDiemService _diaDiemService;
        public DiaDiemMienTrungViewComponent(DiaDiemService diaDiemService)
        {
            this._diaDiemService = diaDiemService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = this._diaDiemService.DiadiemMienTrung();
            if(model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
    }
}

Controllers/KhachSanController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YourTour.Service;

namespace YourTour.Controllers
{
    public class KhachSanController : Controller
    {
        private readonly KhachSanService _khachSanService;
        public KhachSanController(KhachSanService khachSanService)
        {
            this._khachSanService = khachSanService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult DiemDen()
        {
            return View();
        }
        public IActionResult KhachSanThuocDiaDiem(int id)
        {
            var model = this._khachSanService.KsMienTrung(id);
            if(model == null)
            {
                return View("/Views/Shared/PageNotFound.cshtml");
            }
            return View(model);
        }
    }
}

Views/KhachSan/DiemDen.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Khách sạn";
    Layout = "/Views/Shared/_LayoutTour.cshtml";
}
<h2 class="text-capitalize" style="color:red; text-align:center">Khách sạn</h2>
<div class="container py-lg-4 py-sm-3">
    @await Component.InvokeAsync("DiaDiemMienTrung")
</div>

Views/KhachSan/KhachSanThuocDiaDiem.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Khách sạn";
    Layout = "/Views/Shared/_LayoutTour.cshtml";
}
@model IEnumerable<YourTour.Models.ViewModels.KhachSanViewModel>
<h2 class="text-capitalize" style="text-align:center; color:red">Danh sách khách sạn</h2>
<div class="container py-lg-4 py-sm-3">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-3 col-sm-6 col-6 destinations-grids text-center">
                <div class="image-position position-relative">
                    <a href="@Url.Action("DatTourTuChon","DatTour", new { @id = item.ID})">
                        <img src="@Url.Content("/images/khachsan/"+item.Hinhanh)" alt="" height="200" width="600">
                        <p><span class="text-uppercase"><b>@item.Tenks</b></span></p>
                        <p style="color:red">@item.Gia.ToString("#,##") VND</p>
                    </a>
                </div>
            </div>
        }

    </div>
</div>